[package]
name = "uv-wrapper"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uv-bundle"
path = "src/bin/uv-bundle.rs"

[[bin]]
name = "uv-trampoline"
path = "src/bin/uv-trampoline.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

